version: '3'

services:
  app:
    image: taskmanager.jar
    container_name: taskmanager4.jar
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb
    container_name: maria-d4
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: taskmanagersql
      MYSQL_USER: your-username
      MYSQL_PASSWORD: your-password
    ports:
      - "3306:3306"
